<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="wwwroot\uploads\demo-images\**" />
	  <Content Remove="wwwroot\uploads\demo-images\**" />
	  <EmbeddedResource Remove="wwwroot\uploads\demo-images\**" />
	  <None Remove="wwwroot\uploads\demo-images\**" />
	</ItemGroup>

        <ItemGroup>
                <!-- Swagger / OpenAPI -->
                <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
        </ItemGroup>

        <ItemGroup>
          <Folder Include="wwwroot\uploads\features\" />
                <ProjectReference Include="..\Sommerhus.Domain\Sommerhus.Domain.csproj" />
                <ProjectReference Include="..\Sommerhus.Contracts\Sommerhus.Contracts.csproj" />
                <ProjectReference Include="..\Sommerhus.Pricing\Sommerhus.Pricing.csproj" />
                <ProjectReference Include="..\Sommerhus.Application\Sommerhus.Application.csproj" />
                <ProjectReference Include="..\Sommerhus.Repository\Sommerhus.Repository.csproj" />
        </ItemGroup>

</Project>
