<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="wwwroot\uploads\demo-images\**" />
		<Compile Remove="wwwroot\uploads\features\**" />
		<Content Remove="wwwroot\uploads\demo-images\**" />
		<Content Remove="wwwroot\uploads\features\**" />
		<EmbeddedResource Remove="wwwroot\uploads\demo-images\**" />
		<EmbeddedResource Remove="wwwroot\uploads\features\**" />
		<None Remove="wwwroot\uploads\demo-images\**" />
		<None Remove="wwwroot\uploads\features\**" />
	</ItemGroup>

	<ItemGroup>
		<Content Update="sommerhus.db" CopyToPublishDirectory="Never" />
	</ItemGroup>
        <ItemGroup>
                <!-- Swagger / OpenAPI -->
                <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
                <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10" />
                <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10" />
        </ItemGroup>

        <ItemGroup>
                <ProjectReference Include="..\Sommerhus.Domain\Sommerhus.Domain.csproj" />
                <ProjectReference Include="..\Sommerhus.Contracts\Sommerhus.Contracts.csproj" />
                <ProjectReference Include="..\Sommerhus.Application\Sommerhus.Application.csproj" />
                <ProjectReference Include="..\Sommerhus.Repository\Sommerhus.Repository.csproj" />
        </ItemGroup>

        <ItemGroup>
          <Folder Include="wwwroot\uploads\" />
        </ItemGroup>

</Project>
