name: Runner Smoke Test
on:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: self-hosted
    steps:
      - name: Whoami & mkdir & testfile
        shell: pwsh
        run: |
          whoami
          if (!(Test-Path C:\_deploy)) { New-Item -ItemType Directory -Path C:\_deploy | Out-Null }
          Set-Content -Path C:\_deploy\smoke.txt -Value "Hello from GitHub Actions $(Get-Date)"
          Get-ChildItem C:\_deploy
